apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  database-url: "postgresql://{{ .Values.db.credentials.user }}:{{ .Values.db.credentials.password }}@{{ .Release.Name }}-db:5432/{{ .Values.db.credentials.database }}"