apiVersion: v1
kind: PersistentVolume
metadata:
  name: foodneasy-db-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data/foodneasy-db"  # Adjust for your environment