apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodneasy-app
  labels:
    app: foodneasy-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foodneasy-app
  template:
    metadata:
      labels:
        app: foodneasy-app
    spec:
      containers:
      - name: foodneasy-app
        image: liormilliger/liorm-foodneasy:<tag>  # Replace <tag> with your image tag
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: foodneasy-config
              key: database-url
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"