# App settings
app:
  image:
    repository: liormilliger/liorm-foodneasy
    tag: "latest"  # Default tag, override with --set or custom values file
    pullPolicy: IfNotPresent
  replicas: 1
  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
    # limits:
    #   memory: "512Mi"
    #   cpu: "500m"
  service:
    port: 80

# DB settings
db:
  image:
    repository: liormilliger/liorm-foodneasy-db
    tag: "latest"
    pullPolicy: IfNotPresent
  replicas: 1
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    # limits:
    #   memory: "1Gi"
    #   cpu: "500m"
  storage:
    size: "20Gi"
  credentials:
    user: foodneasy_user
    password: foodneasy_pass  # Consider using a Secret outside Helm
    database: foodneasy_db

# Ingress settings
ingress:
  enabled: true
  host: foodneasy.example.com
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /